#!/bin/bash

# Script to help get Railway DATABASE_URL

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           OBTENER DATABASE_URL DE RAILWAY                      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Necesitas el DATABASE_URL real de Railway para migrar."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "OPCIÓN 1: Desde Railway Dashboard (MÁS FÁCIL)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Abre: https://railway.app/dashboard"
echo "2. Busca tu proyecto 'ZIONX' o similar"
echo "3. Click en el servicio 'PostgreSQL' (ícono de base de datos)"
echo "4. Click en tab 'Variables' o 'Connect'"
echo "5. Busca 'DATABASE_URL'"
echo "6. Click en el ícono de 'Copy' o 'Show'"
echo "7. Copia el valor completo"
echo ""
echo "Se verá así:"
echo "postgresql://postgres:AbC123xyz...@containers-us-west-123.railway.app:7543/railway"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "OPCIÓN 2: Usando Railway CLI"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Si tienes Railway CLI instalado:"
echo ""
echo "# Instalar Railway CLI (si no lo tienes)"
echo "npm install -g @railway/cli"
echo ""
echo "# Login"
echo "railway login"
echo ""
echo "# Link al proyecto"
echo "railway link"
echo ""
echo "# Ver variables"
echo "railway variables"
echo ""
echo "# O ejecutar comando con acceso a variables"
echo "railway run env | grep DATABASE_URL"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "OPCIÓN 3: Desde el código del backend en Railway"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Si tu backend ya está desplegado en Railway, puedes:"
echo ""
echo "1. Ve a Railway Dashboard > Tu servicio backend"
echo "2. Click en 'Variables'"
echo "3. Busca DATABASE_URL"
echo "4. Click en 'Show' o el ícono de ojo"
echo "5. Copia el valor"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  NUNCA compartas tu DATABASE_URL públicamente!"
echo "    Contiene credenciales de acceso a tu base de datos."
echo ""
echo "✅ Una vez que tengas el DATABASE_URL:"
echo "   node migrate-to-production.js"
echo ""
